version: "3.8"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: smartorder
      POSTGRES_PASSWORD: smartorder
      POSTGRES_DB: smartorder
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports: ["6379:6379"]

volumes:
  dbdata:
